/* confdefs.h */
#define PACKAGE_NAME "universal-ctags"
#define PACKAGE_TARNAME "universal-ctags"
#define PACKAGE_VERSION "6.0.0"
#define PACKAGE_STRING "universal-ctags 6.0.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "universal-ctags"
#define VERSION "6.0.0"
#define DEFAULT_FILE_FORMAT 2
#define ETAGS "etags"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_WCHAR_H 1
#define HAVE_FNMATCH_H 1
#define HAVE_THREADS_H 1
#define HAVE_LIMITS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_LANGINFO_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_MALLOC_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FEATURES_H 1
#define HAVE_WCTYPE_H 1
#define _ALL_SOURCE 1
#define _DARWIN_C_SOURCE 1
#define _GNU_SOURCE 1
#define _HPUX_ALT_XOPEN_SOCKET_API 1
#define _NETBSD_SOURCE 1
#define _OPENBSD_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#define __STDC_WANT_LIB_EXT2__ 1
#define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#define _TANDEM_SOURCE 1
#define __EXTENSIONS__ 1
#define TMPDIR "/tmp"
#define CASE_INSENSITIVE_FILENAMES 1
#define EXTERNAL_SORT 1
#define HAVE_DIRENT_H 1
#define HAVE_FCNTL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_DIR_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_TYPEOF 1
#define HAVE_STATEMENT_EXPRESSION_EXT 1
#define HAVE_STAT_ST_INO 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_BTOWC 1
#define HAVE_FNMATCH 1
#define HAVE_MBSRTOWCS 1
#define HAVE_ISBLANK 1
#define HAVE_MBSINIT 1
#define HAVE_MBRTOWC 1
#define HAVE_MPROTECT 1
#define HAVE_NL_LANGINFO 1
#define HAVE_ISWCTYPE 1
#define HAVE_WCRTOMB 1
#define HAVE_ISWCNTRL 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_MBSTATE_T 1
#define HAVE_PTHREAD_API 1
#define SETLOCALE_NULL_ALL_MTSAFE 0
#define SETLOCALE_NULL_ONE_MTSAFE 1
#define HAVE_WEAK_SYMBOLS 1
#define HAVE_WINT_T 1
#define HAVE_LONG_LONG_INT 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define restrict __restrict__
#define HAVE_WCHAR_T 1
#define HAVE_WEAK_SYMBOLS 1
#define USE_POSIX_THREADS 1
#define USE_POSIX_THREADS_WEAK 1
#define HAVE_MAP_ANONYMOUS 1
#define HAVE_DECL_ALARM 1
#define HAVE_STDLIB_H 1
#define MALLOC_0_IS_NONNULL 1
#define HAVE__BOOL 1
#define HAVE_DECL_ECVT 1
#define HAVE_DECL_FCVT 1
#define HAVE_DECL_GCVT 1
#define HAVE_DECL_STRNLEN 1
#define _USE_STD_STAT 1
#define HAVE_DECL_EXECVPE 1
#define HAVE_DECL_WCSDUP 1
#define HAVE_TOWLOWER 1
#define HAVE_ALLOCA 1
#define GNULIB_TEST_BTOWC 1
#define HAVE___BUILTIN_EXPECT 1
#define FLEXIBLE_ARRAY_MEMBER /**/
#define GNULIB_TEST_FNMATCH 1
#define GNULIB_ISBLANK 1
#define HAVE___INLINE 1
#define GNULIB_TEST_LOCALECONV 1
#define HAVE_PTHREAD_RWLOCK 1
#define HAVE_PTHREAD_MUTEX_RECURSIVE 1
#define GNULIB_LOCK 1
#define GNULIB_TEST_MBRTOWC 1
#define GNULIB_TEST_MBSINIT 1
#define GNULIB_TEST_MBSRTOWCS 1
#define HAVE_MBTOWC 1
#define GNULIB_TEST_MBTOWC 1
#define GNULIB_TEST_MEMCHR 1
#define HAVE_MEMPCPY 1
#define GNULIB_TEST_MEMPCPY 1
#define FUNC_NL_LANGINFO_YESEXPR_WORKS 1
#define NL_LANGINFO_MTSAFE 1
#define REPLACE_NL_LANGINFO 1
#define GNULIB_TEST_NL_LANGINFO 1
#define _REGEX_INCLUDE_LIMITS_H 1
#define _REGEX_LARGE_OFFSETS 1
#define re_syntax_options rpl_re_syntax_options
#define re_set_syntax rpl_re_set_syntax
#define re_compile_pattern rpl_re_compile_pattern
#define re_compile_fastmap rpl_re_compile_fastmap
#define re_search rpl_re_search
#define re_search_2 rpl_re_search_2
#define re_match rpl_re_match
#define re_match_2 rpl_re_match_2
#define re_set_registers rpl_re_set_registers
#define re_comp rpl_re_comp
#define re_exec rpl_re_exec
#define regcomp rpl_regcomp
#define regexec rpl_regexec
#define regerror rpl_regerror
#define regfree rpl_regfree
#define HAVE_DECL_ISBLANK 1
#define SETLOCALE_NULL_ALL_MTSAFE 0
#define SETLOCALE_NULL_ONE_MTSAFE 1
#define HAVE_WEAK_SYMBOLS 1
#define HAVE_VISIBILITY 1
#define GNULIB_TEST_SETLOCALE_NULL 1
#define GNULIB_TEST_STRNLEN 1
