version: '3.8'

services:
  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: .
      dockerfile: org.dockerfile
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
    - type: bind
      source: ${HOME}
      target: /home
      source: .
      target: /home/node/app
      source: ./node_modules
      target: /home/node/app/node_modules
      ## MacOS
      source: ${HOME}/Library/pnpm/store
      target: /home/node/app/.pnpm-store
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
