#!/usr/bin/env bash
gnostr-set-relays 2>/tmp/gnostr-org.log || echo
(echo `pwd`) & clear && \
# gnostr-org sub-shell process
#
#
NVM_VERSION=v16.20.2
touch .nvmrc
echo $NVM_VERSION > .nvmrc
if ! grep -q "$NVM_VERSION" .nvmrc; then echo "$NVM_VERSION" > .nvmrc; fi;\
touch .gitignore
if ! grep -q ".nvmrc" .gitignore; then echo ".nvmrc" >> .gitignore; fi;\

export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] >/dev/null && \. "$NVM_DIR/nvm.sh" >/dev/null && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" && echo "gnostr-org:nvm:node -v $NVM_VERSION" && nvm install $NVM_VERSION >/tmp/gnostr-org.log 2>&1 && nvm use --silent 2>/tmp/gnostr-org.log \

(\

if ! grep -q ".gnostr/org" .gitignore; then echo ".gnostr/org" >> .gitignore; fi;\

mkdir -p .gnostr >/tmp/gnostr-org.log;\
[ ! -d .gnostr/org ] && echo "gnostr-org:git:installing .gnostr/org"
[ ! -d .gnostr/org ] && git clone --depth 1 --branch master https://github.com/gnostr-org/gnostr-org.git .gnostr/org >/tmp/gnostr-org.log 2>&1; \
[   -d .gnostr/org ] && echo "gnostr-org:git:updating .gnostr/org"
[   -d .gnostr/org ] && cd .gnostr/org && git reset --hard 2>/tmp/gnostr-org.log && git pull -f origin master 2>/tmp/gnostr-org.log && echo ".gnostr/org" >> .gitignore >/tmp/gnostr-org.log 2>&1 &&  make run -k > /tmp/gnostr-org.log 2>&1;\
)#2>/tmp/gnostr-org.log;

