#!/usr/bin/env bash
pushd `pwd`
git clone https://github.com/gnostr-org/gnostr-act.git public/gnostr-act >/tmp/gnostr.org.log || git -C public/gnostr-act status
if [ "$(uname -s)" == "Linux" ]; then
sudo apt-get update;
sudo rm -rf /usr/local/go;
wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz;
sudo tar -xvf go1.21.0.linux-amd64.tar.gz;
sudo mv go /usr/local;
export GOROOT=/usr/local/go;
export GOPATH=$HOME/go;
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
source ~/.profile;
echo $GOROOT;
echo $GOPATH;
echo $PATH;
pushd public/gnostr-act && make install
fi
if [ "$(uname -s)" == "Darwin" ]; then
sudo rm -rf /usr/local/go;
wget https://go.dev/dl/go1.21.0.darwin-amd64.tar.gz;
sudo tar -xvf go1.21.0.darwin-amd64.tar.gz;
sudo mv go /usr/local;
export GOROOT=/usr/local/go;
export GOPATH=$HOME/go;
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
source ~/.profile;
echo $GOROOT;
echo $GOPATH;
echo $PATH;
pushd public/gnostr-act && make install
fi
popd
popd
make public install
