BEGIN {
D["PACKAGE_NAME"]=" \"universal-ctags\""
D["PACKAGE_TARNAME"]=" \"universal-ctags\""
D["PACKAGE_VERSION"]=" \"6.0.0\""
D["PACKAGE_STRING"]=" \"universal-ctags 6.0.0\""
D["PACKAGE_BUGREPORT"]=" \"\""
D["PACKAGE_URL"]=" \"\""
D["PACKAGE"]=" \"universal-ctags\""
D["VERSION"]=" \"6.0.0\""
D["DEFAULT_FILE_FORMAT"]=" 2"
D["ETAGS"]=" \"etags\""
D["STDC_HEADERS"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_STRING_H"]=" 1"
D["HAVE_MEMORY_H"]=" 1"
D["HAVE_STRINGS_H"]=" 1"
D["HAVE_INTTYPES_H"]=" 1"
D["HAVE_STDINT_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_WCHAR_H"]=" 1"
D["HAVE_FNMATCH_H"]=" 1"
D["HAVE_THREADS_H"]=" 1"
D["HAVE_LIMITS_H"]=" 1"
D["HAVE_INTTYPES_H"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_STDINT_H"]=" 1"
D["HAVE_LANGINFO_H"]=" 1"
D["HAVE_SYS_MMAN_H"]=" 1"
D["HAVE_MALLOC_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_FEATURES_H"]=" 1"
D["HAVE_WCTYPE_H"]=" 1"
D["_ALL_SOURCE"]=" 1"
D["_DARWIN_C_SOURCE"]=" 1"
D["_GNU_SOURCE"]=" 1"
D["_HPUX_ALT_XOPEN_SOCKET_API"]=" 1"
D["_NETBSD_SOURCE"]=" 1"
D["_OPENBSD_SOURCE"]=" 1"
D["_POSIX_PTHREAD_SEMANTICS"]=" 1"
D["__STDC_WANT_IEC_60559_ATTRIBS_EXT__"]=" 1"
D["__STDC_WANT_IEC_60559_BFP_EXT__"]=" 1"
D["__STDC_WANT_IEC_60559_DFP_EXT__"]=" 1"
D["__STDC_WANT_IEC_60559_FUNCS_EXT__"]=" 1"
D["__STDC_WANT_IEC_60559_TYPES_EXT__"]=" 1"
D["__STDC_WANT_LIB_EXT2__"]=" 1"
D["__STDC_WANT_MATH_SPEC_FUNCS__"]=" 1"
D["_TANDEM_SOURCE"]=" 1"
D["__EXTENSIONS__"]=" 1"
D["TMPDIR"]=" \"/tmp\""
D["CASE_INSENSITIVE_FILENAMES"]=" 1"
D["EXTERNAL_SORT"]=" 1"
D["HAVE_DIRENT_H"]=" 1"
D["HAVE_FCNTL_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_SYS_DIR_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_SYS_WAIT_H"]=" 1"
D["HAVE_STDBOOL_H"]=" 1"
D["HAVE_TYPEOF"]=" 1"
D["HAVE_STATEMENT_EXPRESSION_EXT"]=" 1"
D["HAVE_STAT_ST_INO"]=" 1"
D["HAVE_ALLOCA_H"]=" 1"
D["HAVE_ALLOCA"]=" 1"
D["HAVE_BTOWC"]=" 1"
D["HAVE_FNMATCH"]=" 1"
D["HAVE_MBSRTOWCS"]=" 1"
D["HAVE_ISBLANK"]=" 1"
D["HAVE_MBSINIT"]=" 1"
D["HAVE_MBRTOWC"]=" 1"
D["HAVE_MPROTECT"]=" 1"
D["HAVE_NL_LANGINFO"]=" 1"
D["HAVE_ISWCTYPE"]=" 1"
D["HAVE_WCRTOMB"]=" 1"
D["HAVE_ISWCNTRL"]=" 1"
D["HAVE_LANGINFO_CODESET"]=" 1"
D["HAVE_MBSTATE_T"]=" 1"
D["HAVE_PTHREAD_API"]=" 1"
D["SETLOCALE_NULL_ALL_MTSAFE"]=" 0"
D["SETLOCALE_NULL_ONE_MTSAFE"]=" 1"
D["HAVE_WEAK_SYMBOLS"]=" 1"
D["HAVE_WINT_T"]=" 1"
D["HAVE_LONG_LONG_INT"]=" 1"
D["HAVE_UNSIGNED_LONG_LONG_INT"]=" 1"
D["restrict"]=" __restrict__"
D["HAVE_WCHAR_T"]=" 1"
D["HAVE_WEAK_SYMBOLS"]=" 1"
D["USE_POSIX_THREADS"]=" 1"
D["USE_POSIX_THREADS_WEAK"]=" 1"
D["HAVE_MAP_ANONYMOUS"]=" 1"
D["HAVE_DECL_ALARM"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["MALLOC_0_IS_NONNULL"]=" 1"
D["HAVE__BOOL"]=" 1"
D["HAVE_DECL_ECVT"]=" 1"
D["HAVE_DECL_FCVT"]=" 1"
D["HAVE_DECL_GCVT"]=" 1"
D["HAVE_DECL_STRNLEN"]=" 1"
D["_USE_STD_STAT"]=" 1"
D["HAVE_DECL_EXECVPE"]=" 1"
D["HAVE_DECL_WCSDUP"]=" 1"
D["HAVE_TOWLOWER"]=" 1"
D["HAVE_ALLOCA"]=" 1"
D["GNULIB_TEST_BTOWC"]=" 1"
D["HAVE___BUILTIN_EXPECT"]=" 1"
D["FLEXIBLE_ARRAY_MEMBER"]=" /**/"
D["GNULIB_TEST_FNMATCH"]=" 1"
D["GNULIB_ISBLANK"]=" 1"
D["HAVE___INLINE"]=" 1"
D["GNULIB_TEST_LOCALECONV"]=" 1"
D["HAVE_PTHREAD_RWLOCK"]=" 1"
D["HAVE_PTHREAD_MUTEX_RECURSIVE"]=" 1"
D["GNULIB_LOCK"]=" 1"
D["GNULIB_TEST_MBRTOWC"]=" 1"
D["GNULIB_TEST_MBSINIT"]=" 1"
D["GNULIB_TEST_MBSRTOWCS"]=" 1"
D["HAVE_MBTOWC"]=" 1"
D["GNULIB_TEST_MBTOWC"]=" 1"
D["GNULIB_TEST_MEMCHR"]=" 1"
D["HAVE_MEMPCPY"]=" 1"
D["GNULIB_TEST_MEMPCPY"]=" 1"
D["FUNC_NL_LANGINFO_YESEXPR_WORKS"]=" 1"
D["NL_LANGINFO_MTSAFE"]=" 1"
D["REPLACE_NL_LANGINFO"]=" 1"
D["GNULIB_TEST_NL_LANGINFO"]=" 1"
D["_REGEX_INCLUDE_LIMITS_H"]=" 1"
D["_REGEX_LARGE_OFFSETS"]=" 1"
D["re_syntax_options"]=" rpl_re_syntax_options"
D["re_set_syntax"]=" rpl_re_set_syntax"
D["re_compile_pattern"]=" rpl_re_compile_pattern"
D["re_compile_fastmap"]=" rpl_re_compile_fastmap"
D["re_search"]=" rpl_re_search"
D["re_search_2"]=" rpl_re_search_2"
D["re_match"]=" rpl_re_match"
D["re_match_2"]=" rpl_re_match_2"
D["re_set_registers"]=" rpl_re_set_registers"
D["re_comp"]=" rpl_re_comp"
D["re_exec"]=" rpl_re_exec"
D["regcomp"]=" rpl_regcomp"
D["regexec"]=" rpl_regexec"
D["regerror"]=" rpl_regerror"
D["regfree"]=" rpl_regfree"
D["HAVE_DECL_ISBLANK"]=" 1"
D["SETLOCALE_NULL_ALL_MTSAFE"]=" 0"
D["SETLOCALE_NULL_ONE_MTSAFE"]=" 1"
D["HAVE_WEAK_SYMBOLS"]=" 1"
D["HAVE_VISIBILITY"]=" 1"
D["GNULIB_TEST_SETLOCALE_NULL"]=" 1"
D["GNULIB_TEST_STRNLEN"]=" 1"
D["GNULIB_TEST_WCRTOMB"]=" 1"
D["GNULIB_TEST_WMEMCHR"]=" 1"
D["GNULIB_TEST_WMEMPCPY"]=" 1"
D["HAVE_ASPRINTF"]=" 1"
D["HAVE_STRCASECMP"]=" 1"
D["HAVE_STRNCASECMP"]=" 1"
D["HAVE_MKSTEMP"]=" 1"
D["HAVE_OPENDIR"]=" 1"
D["HAVE_STRERROR"]=" 1"
D["HAVE_TRUNCATE"]=" 1"
D["HAVE_SETENV"]=" 1"
D["HAVE_SCANDIR"]=" 1"
D["HAVE_DIRENT_H"]=" 1"
D["HAVE_ICONV"]=" 1"
D["HAVE_DECL___ENVIRON"]=" 0"
D["HAVE_DECL__NSGETENVIRON"]=" 0"
D["HAVE_DECL_STRNLEN"]=" 1"
D["HAVE_MBLEN"]=" 1"
  for (key in D) D_is_set[key] = 1
  FS = ""
}
/^[\t ]*#[\t ]*(define|undef)[\t ]+[_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ][_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789]*([\t (]|$)/ {
  line = $ 0
  split(line, arg, " ")
  if (arg[1] == "#") {
    defundef = arg[2]
    mac1 = arg[3]
  } else {
    defundef = substr(arg[1], 2)
    mac1 = arg[2]
  }
  split(mac1, mac2, "(") #)
  macro = mac2[1]
  prefix = substr(line, 1, index(line, defundef) - 1)
  if (D_is_set[macro]) {
    # Preserve the white space surrounding the "#".
    print prefix "define", macro P[macro] D[macro]
    next
  } else {
    # Replace #undef with comments.  This is necessary, for example,
    # in the case of _POSIX_SOURCE, which is predefined and required
    # on some systems where configure will not decide to define it.
    if (defundef == "undef") {
      print "/*", prefix defundef, macro, "*/"
      next
    }
  }
}
{ print }
